CREATE TABLE USERS(
    ID NUMBER PRIMARY KEY UNIQUE, --CHANGE NUMBER TO INTEGER FOR POSTGRESQL
    FIRST_NAME VARCHAR2(30) NOT NULL,
    LAST_NAME VARCHAR2(30) NOT NULL,
    USER_ID VARCHAR2(30) NOT NULL
);

INSERT INTO USERS(ID, FIRST_NAME, LAST_NAME, USER_ID) values (1,'Cesar','Amadori','CAMADORI');
INSERT INTO USERS(ID, FIRST_NAME, LAST_NAME, USER_ID) values (2,'Tomas','Beraldi','TBERALDI');

CREATE TABLE TIME_USER(
    USER_ID NUMBER PRIMARY KEY UNIQUE,
    FIRST_NAME VARCHAR2(30) NOT NULL,
    LAST_NAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL
);

INSERT INTO TIME_USER(USER_ID, FIRST_NAME, LAST_NAME, EMAIL) values (1,'Cesar','Amadori','cesargamadori@gmail.com');

CREATE TABLE TASK(
    TASK_ID NUMBER PRIMARY KEY UNIQUE,
    USER_ID NUMBER NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    DETAILS VARCHAR2(200),
    IS_COMPLETED NUMBER(1) NOT NULL,
    STATE VARCHAR2(15) NOT NULL,
    CURRENT_SPRINT VARCHAR2(50) NOT NULL,
    EXPECTED_COMPLETION_TIME VARCHAR2(10) NOT NULL,
    TYPE VARCHAR(20) NOT NULL
);

CREATE SEQUENCE "TASK_ID_SEQ"
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE "TIME_ID_SEQ"
    MINVALUE 1
    MAXVALUE 999999999
    INCREMENT BY 1
    START WITH 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TIME_LOG(
        TIME_ID NUMBER PRIMARY KEY UNIQUE,
        TASK_ID NUMBER NOT NULL,
        START_TIME TIMESTAMP NOT NULL,
        END_TIME TIMESTAMP
)